//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Logistika123
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Докум поставки.
    /// </summary>
    // *** Start programmer edit section *** (ДокумПоставки CustomAttributes)

    // *** End programmer edit section *** (ДокумПоставки CustomAttributes)
    [AutoAltered()]
    [Caption("Документ поставки")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокумПоставкиE", new string[] {
            "Дата as \'Дата\'",
            "НомДокПостав as \'Номер документа поставки\'",
            "Организация as \'Наименование организации\'",
            "Организация.НаимОрганиз as \'Наименование организации\'",
            "Сотрудники as \'Ответственный\'",
            "Сотрудники.ФИОСотруд as \'Ответственный\'",
            "Клиенты as \'Наименование заказчика\'",
            "Клиенты.Заказчик as \'Заказчик\'",
            "Клиенты.Телефон as \'Телефон\'",
            "Клиенты.АдресПоставки as \'Адрес поставки\'"}, Hidden=new string[] {
            "Организация.НаимОрганиз",
            "Сотрудники.ФИОСотруд",
            "Клиенты.Заказчик"})]
    [AssociatedDetailViewAttribute("ДокумПоставкиE", "ИнфОЗаказе", "ИнфОЗаказеE", true, "", "Информация о заказе", true, new string[] {
            ""})]
    [MasterViewDefineAttribute("ДокумПоставкиE", "Организация", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НаимОрганиз")]
    [MasterViewDefineAttribute("ДокумПоставкиE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИОСотруд")]
    [MasterViewDefineAttribute("ДокумПоставкиE", "Клиенты", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Заказчик")]
    [View("ДокумПоставкиL", new string[] {
            "Дата as \'Дата\'",
            "НомДокПостав as \'Номер документа поставки\'",
            "Организация.НаимОрганиз as \'Наименование организации\'",
            "Сотрудники.ФИОСотруд as \'Ответственный\'",
            "Клиенты.Заказчик as \'Заказчик\'"})]
    public class ДокумПоставки : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private int fНомДокПостав;
        
        private IIS.Logistika123.Сотрудники fСотрудники;
        
        private IIS.Logistika123.Организация fОрганизация;
        
        private IIS.Logistika123.Клиенты fКлиенты;
        
        private IIS.Logistika123.DetailArrayOfИнфОЗаказе fИнфОЗаказе;
        
        // *** Start programmer edit section *** (ДокумПоставки CustomMembers)

        // *** End programmer edit section *** (ДокумПоставки CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.Дата CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.Дата Get start)

                // *** End programmer edit section *** (ДокумПоставки.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ДокумПоставки.Дата Get end)

                // *** End programmer edit section *** (ДокумПоставки.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.Дата Set start)

                // *** End programmer edit section *** (ДокумПоставки.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ДокумПоставки.Дата Set end)

                // *** End programmer edit section *** (ДокумПоставки.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомДокПостав.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.НомДокПостав CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.НомДокПостав CustomAttributes)
        public virtual int НомДокПостав
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.НомДокПостав Get start)

                // *** End programmer edit section *** (ДокумПоставки.НомДокПостав Get start)
                int result = this.fНомДокПостав;
                // *** Start programmer edit section *** (ДокумПоставки.НомДокПостав Get end)

                // *** End programmer edit section *** (ДокумПоставки.НомДокПостав Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.НомДокПостав Set start)

                // *** End programmer edit section *** (ДокумПоставки.НомДокПостав Set start)
                this.fНомДокПостав = value;
                // *** Start programmer edit section *** (ДокумПоставки.НомДокПостав Set end)

                // *** End programmer edit section *** (ДокумПоставки.НомДокПостав Set end)
            }
        }
        
        /// <summary>
        /// Докум поставки.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.Клиенты CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.Клиенты CustomAttributes)
        [PropertyStorage(new string[] {
                "Клиенты"})]
        [NotNull()]
        public virtual IIS.Logistika123.Клиенты Клиенты
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.Клиенты Get start)

                // *** End programmer edit section *** (ДокумПоставки.Клиенты Get start)
                IIS.Logistika123.Клиенты result = this.fКлиенты;
                // *** Start programmer edit section *** (ДокумПоставки.Клиенты Get end)

                // *** End programmer edit section *** (ДокумПоставки.Клиенты Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.Клиенты Set start)

                // *** End programmer edit section *** (ДокумПоставки.Клиенты Set start)
                this.fКлиенты = value;
                // *** Start programmer edit section *** (ДокумПоставки.Клиенты Set end)

                // *** End programmer edit section *** (ДокумПоставки.Клиенты Set end)
            }
        }
        
        /// <summary>
        /// Докум поставки.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.Организация CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.Организация CustomAttributes)
        [PropertyStorage(new string[] {
                "Организация"})]
        [NotNull()]
        public virtual IIS.Logistika123.Организация Организация
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.Организация Get start)

                // *** End programmer edit section *** (ДокумПоставки.Организация Get start)
                IIS.Logistika123.Организация result = this.fОрганизация;
                // *** Start programmer edit section *** (ДокумПоставки.Организация Get end)

                // *** End programmer edit section *** (ДокумПоставки.Организация Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.Организация Set start)

                // *** End programmer edit section *** (ДокумПоставки.Организация Set start)
                this.fОрганизация = value;
                // *** Start programmer edit section *** (ДокумПоставки.Организация Set end)

                // *** End programmer edit section *** (ДокумПоставки.Организация Set end)
            }
        }
        
        /// <summary>
        /// Докум поставки.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Logistika123.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.Сотрудники Get start)

                // *** End programmer edit section *** (ДокумПоставки.Сотрудники Get start)
                IIS.Logistika123.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ДокумПоставки.Сотрудники Get end)

                // *** End programmer edit section *** (ДокумПоставки.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.Сотрудники Set start)

                // *** End programmer edit section *** (ДокумПоставки.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ДокумПоставки.Сотрудники Set end)

                // *** End programmer edit section *** (ДокумПоставки.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Докум поставки.
        /// </summary>
        // *** Start programmer edit section *** (ДокумПоставки.ИнфОЗаказе CustomAttributes)

        // *** End programmer edit section *** (ДокумПоставки.ИнфОЗаказе CustomAttributes)
        public virtual IIS.Logistika123.DetailArrayOfИнфОЗаказе ИнфОЗаказе
        {
            get
            {
                // *** Start programmer edit section *** (ДокумПоставки.ИнфОЗаказе Get start)

                // *** End programmer edit section *** (ДокумПоставки.ИнфОЗаказе Get start)
                if ((this.fИнфОЗаказе == null))
                {
                    this.fИнфОЗаказе = new IIS.Logistika123.DetailArrayOfИнфОЗаказе(this);
                }
                IIS.Logistika123.DetailArrayOfИнфОЗаказе result = this.fИнфОЗаказе;
                // *** Start programmer edit section *** (ДокумПоставки.ИнфОЗаказе Get end)

                // *** End programmer edit section *** (ДокумПоставки.ИнфОЗаказе Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумПоставки.ИнфОЗаказе Set start)

                // *** End programmer edit section *** (ДокумПоставки.ИнфОЗаказе Set start)
                this.fИнфОЗаказе = value;
                // *** Start programmer edit section *** (ДокумПоставки.ИнфОЗаказе Set end)

                // *** End programmer edit section *** (ДокумПоставки.ИнфОЗаказе Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокумПоставкиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокумПоставкиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокумПоставкиE", typeof(IIS.Logistika123.ДокумПоставки));
                }
            }
            
            /// <summary>
            /// "ДокумПоставкиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокумПоставкиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокумПоставкиL", typeof(IIS.Logistika123.ДокумПоставки));
                }
            }
        }
    }
}
