//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vapro
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Докум расп.
    /// </summary>
    // *** Start programmer edit section *** (ДокумРасп CustomAttributes)

    // *** End programmer edit section *** (ДокумРасп CustomAttributes)
    [AutoAltered()]
    [Caption("Документ распределения")]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("ДокумРаспE", new string[] {
            "Дата as \'Дата\'",
            "НомерДокРаспр as \'Номер документа распределения\'",
            "ДокумПоставки as \'Номер документа поставки\'",
            "ДокумПоставки.НомДокПостав as \'Номер документа распределения\'",
            "ДокумПоставки.Организация.НаимОрганиз as \'Наименование организации\'",
            "Сотрудники as \'Ответственный\'",
            "Сотрудники.ФИОСотруд as \'ФИО сотрудника\'",
            "ДокумПоставки.Клиенты.Заказчик as \'Заказчик\'",
            "ДокумПоставки.Клиенты.Телефон as \'Телефон\'",
            "ДокумПоставки.Клиенты.АдресПоставки as \'Адрес поставки\'",
            "ПунктПогрузки as \'Адрес пункта погрузки\'",
            "ПунктПогрузки.Адрес as \'Адрес пункта погрузки\'",
            "СписокБарж as \'Номер баржи\'",
            "СписокБарж.НомерБаржи as \'Номер баржи\'",
            "СписокКонтей as \'Номер контейнера\'",
            "СписокКонтей.НомерКонтей as \'Номер контейнера\'"}, Hidden=new string[] {
            "ДокумПоставки.НомДокПостав",
            "Сотрудники.ФИОСотруд",
            "ПунктПогрузки.Адрес",
            "СписокБарж.НомерБаржи",
            "СписокКонтей.НомерКонтей"})]
    [MasterViewDefineAttribute("ДокумРаспE", "ДокумПоставки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомДокПостав")]
    [MasterViewDefineAttribute("ДокумРаспE", "Сотрудники", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "ФИОСотруд")]
    [MasterViewDefineAttribute("ДокумРаспE", "ПунктПогрузки", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "Адрес")]
    [MasterViewDefineAttribute("ДокумРаспE", "СписокБарж", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерБаржи")]
    [MasterViewDefineAttribute("ДокумРаспE", "СписокКонтей", ICSSoft.STORMNET.LookupTypeEnum.Standard, "", "НомерКонтей")]
    [View("ДокумРаспL", new string[] {
            "Дата as \'Дата\'",
            "НомерДокРаспр as \'Номер документа распределения по баржам\'",
            "ДокумПоставки.НомДокПостав as \'Номер документа поставки\'",
            "Сотрудники.ФИОСотруд as \'Ответсвенный\'",
            "ПунктПогрузки.Адрес as \'Адрес пункта погрузки\'",
            "СписокБарж.НомерБаржи as \'Номер баржи\'",
            "СписокКонтей.НомерКонтей as \'Номер контейнера\'"})]
    public class ДокумРасп : ICSSoft.STORMNET.DataObject
    {
        
        private System.DateTime fДата = System.DateTime.Now;
        
        private int fНомерДокРаспр;
        
        private IIS.Vapro.СписокБарж fСписокБарж;
        
        private IIS.Vapro.ПунктПогрузки fПунктПогрузки;
        
        private IIS.Vapro.Сотрудники fСотрудники;
        
        private IIS.Vapro.СписокКонтей fСписокКонтей;
        
        private IIS.Vapro.ДокумПоставки fДокумПоставки;
        
        // *** Start programmer edit section *** (ДокумРасп CustomMembers)

        // *** End programmer edit section *** (ДокумРасп CustomMembers)

        
        /// <summary>
        /// Дата.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРасп.Дата CustomAttributes)

        // *** End programmer edit section *** (ДокумРасп.Дата CustomAttributes)
        public virtual System.DateTime Дата
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРасп.Дата Get start)

                // *** End programmer edit section *** (ДокумРасп.Дата Get start)
                System.DateTime result = this.fДата;
                // *** Start programmer edit section *** (ДокумРасп.Дата Get end)

                // *** End programmer edit section *** (ДокумРасп.Дата Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРасп.Дата Set start)

                // *** End programmer edit section *** (ДокумРасп.Дата Set start)
                this.fДата = value;
                // *** Start programmer edit section *** (ДокумРасп.Дата Set end)

                // *** End programmer edit section *** (ДокумРасп.Дата Set end)
            }
        }
        
        /// <summary>
        /// НомерДокРаспр.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРасп.НомерДокРаспр CustomAttributes)

        // *** End programmer edit section *** (ДокумРасп.НомерДокРаспр CustomAttributes)
        public virtual int НомерДокРаспр
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРасп.НомерДокРаспр Get start)

                // *** End programmer edit section *** (ДокумРасп.НомерДокРаспр Get start)
                int result = this.fНомерДокРаспр;
                // *** Start programmer edit section *** (ДокумРасп.НомерДокРаспр Get end)

                // *** End programmer edit section *** (ДокумРасп.НомерДокРаспр Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРасп.НомерДокРаспр Set start)

                // *** End programmer edit section *** (ДокумРасп.НомерДокРаспр Set start)
                this.fНомерДокРаспр = value;
                // *** Start programmer edit section *** (ДокумРасп.НомерДокРаспр Set end)

                // *** End programmer edit section *** (ДокумРасп.НомерДокРаспр Set end)
            }
        }
        
        /// <summary>
        /// Докум расп.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРасп.ДокумПоставки CustomAttributes)

        // *** End programmer edit section *** (ДокумРасп.ДокумПоставки CustomAttributes)
        [PropertyStorage(new string[] {
                "ДокумПоставки"})]
        [NotNull()]
        public virtual IIS.Vapro.ДокумПоставки ДокумПоставки
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРасп.ДокумПоставки Get start)

                // *** End programmer edit section *** (ДокумРасп.ДокумПоставки Get start)
                IIS.Vapro.ДокумПоставки result = this.fДокумПоставки;
                // *** Start programmer edit section *** (ДокумРасп.ДокумПоставки Get end)

                // *** End programmer edit section *** (ДокумРасп.ДокумПоставки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРасп.ДокумПоставки Set start)

                // *** End programmer edit section *** (ДокумРасп.ДокумПоставки Set start)
                this.fДокумПоставки = value;
                // *** Start programmer edit section *** (ДокумРасп.ДокумПоставки Set end)

                // *** End programmer edit section *** (ДокумРасп.ДокумПоставки Set end)
            }
        }
        
        /// <summary>
        /// Докум расп.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРасп.ПунктПогрузки CustomAttributes)

        // *** End programmer edit section *** (ДокумРасп.ПунктПогрузки CustomAttributes)
        [PropertyStorage(new string[] {
                "ПунктПогрузки"})]
        [NotNull()]
        public virtual IIS.Vapro.ПунктПогрузки ПунктПогрузки
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРасп.ПунктПогрузки Get start)

                // *** End programmer edit section *** (ДокумРасп.ПунктПогрузки Get start)
                IIS.Vapro.ПунктПогрузки result = this.fПунктПогрузки;
                // *** Start programmer edit section *** (ДокумРасп.ПунктПогрузки Get end)

                // *** End programmer edit section *** (ДокумРасп.ПунктПогрузки Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРасп.ПунктПогрузки Set start)

                // *** End programmer edit section *** (ДокумРасп.ПунктПогрузки Set start)
                this.fПунктПогрузки = value;
                // *** Start programmer edit section *** (ДокумРасп.ПунктПогрузки Set end)

                // *** End programmer edit section *** (ДокумРасп.ПунктПогрузки Set end)
            }
        }
        
        /// <summary>
        /// Докум расп.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРасп.Сотрудники CustomAttributes)

        // *** End programmer edit section *** (ДокумРасп.Сотрудники CustomAttributes)
        [PropertyStorage(new string[] {
                "Сотрудники"})]
        [NotNull()]
        public virtual IIS.Vapro.Сотрудники Сотрудники
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРасп.Сотрудники Get start)

                // *** End programmer edit section *** (ДокумРасп.Сотрудники Get start)
                IIS.Vapro.Сотрудники result = this.fСотрудники;
                // *** Start programmer edit section *** (ДокумРасп.Сотрудники Get end)

                // *** End programmer edit section *** (ДокумРасп.Сотрудники Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРасп.Сотрудники Set start)

                // *** End programmer edit section *** (ДокумРасп.Сотрудники Set start)
                this.fСотрудники = value;
                // *** Start programmer edit section *** (ДокумРасп.Сотрудники Set end)

                // *** End programmer edit section *** (ДокумРасп.Сотрудники Set end)
            }
        }
        
        /// <summary>
        /// Докум расп.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРасп.СписокБарж CustomAttributes)

        // *** End programmer edit section *** (ДокумРасп.СписокБарж CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокБарж"})]
        [NotNull()]
        public virtual IIS.Vapro.СписокБарж СписокБарж
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРасп.СписокБарж Get start)

                // *** End programmer edit section *** (ДокумРасп.СписокБарж Get start)
                IIS.Vapro.СписокБарж result = this.fСписокБарж;
                // *** Start programmer edit section *** (ДокумРасп.СписокБарж Get end)

                // *** End programmer edit section *** (ДокумРасп.СписокБарж Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРасп.СписокБарж Set start)

                // *** End programmer edit section *** (ДокумРасп.СписокБарж Set start)
                this.fСписокБарж = value;
                // *** Start programmer edit section *** (ДокумРасп.СписокБарж Set end)

                // *** End programmer edit section *** (ДокумРасп.СписокБарж Set end)
            }
        }
        
        /// <summary>
        /// Докум расп.
        /// </summary>
        // *** Start programmer edit section *** (ДокумРасп.СписокКонтей CustomAttributes)

        // *** End programmer edit section *** (ДокумРасп.СписокКонтей CustomAttributes)
        [PropertyStorage(new string[] {
                "СписокКонтей"})]
        [NotNull()]
        public virtual IIS.Vapro.СписокКонтей СписокКонтей
        {
            get
            {
                // *** Start programmer edit section *** (ДокумРасп.СписокКонтей Get start)

                // *** End programmer edit section *** (ДокумРасп.СписокКонтей Get start)
                IIS.Vapro.СписокКонтей result = this.fСписокКонтей;
                // *** Start programmer edit section *** (ДокумРасп.СписокКонтей Get end)

                // *** End programmer edit section *** (ДокумРасп.СписокКонтей Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (ДокумРасп.СписокКонтей Set start)

                // *** End programmer edit section *** (ДокумРасп.СписокКонтей Set start)
                this.fСписокКонтей = value;
                // *** Start programmer edit section *** (ДокумРасп.СписокКонтей Set end)

                // *** End programmer edit section *** (ДокумРасп.СписокКонтей Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "ДокумРаспE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокумРаспE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокумРаспE", typeof(IIS.Vapro.ДокумРасп));
                }
            }
            
            /// <summary>
            /// "ДокумРаспL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View ДокумРаспL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("ДокумРаспL", typeof(IIS.Vapro.ДокумРасп));
                }
            }
        }
    }
}
