//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IIS.Vapro
{
    using System;
    using System.Xml;
    using ICSSoft.STORMNET;
    
    
    // *** Start programmer edit section *** (Using statements)

    // *** End programmer edit section *** (Using statements)


    /// <summary>
    /// Сотрудники.
    /// </summary>
    // *** Start programmer edit section *** (Сотрудники CustomAttributes)

    // *** End programmer edit section *** (Сотрудники CustomAttributes)
    [AutoAltered()]
    [AccessType(ICSSoft.STORMNET.AccessType.none)]
    [View("СотрудникиE", new string[] {
            "ФИОСотруд as \'ФИО сотрудника\'"})]
    [View("СотрудникиL", new string[] {
            "ФИОСотруд as \'ФИО сотрудника\'"})]
    public class Сотрудники : ICSSoft.STORMNET.DataObject
    {
        
        private string fФИОСотруд;
        
        // *** Start programmer edit section *** (Сотрудники CustomMembers)

        // *** End programmer edit section *** (Сотрудники CustomMembers)

        
        /// <summary>
        /// ФИОСотруд.
        /// </summary>
        // *** Start programmer edit section *** (Сотрудники.ФИОСотруд CustomAttributes)

        // *** End programmer edit section *** (Сотрудники.ФИОСотруд CustomAttributes)
        [StrLen(255)]
        public virtual string ФИОСотруд
        {
            get
            {
                // *** Start programmer edit section *** (Сотрудники.ФИОСотруд Get start)

                // *** End programmer edit section *** (Сотрудники.ФИОСотруд Get start)
                string result = this.fФИОСотруд;
                // *** Start programmer edit section *** (Сотрудники.ФИОСотруд Get end)

                // *** End programmer edit section *** (Сотрудники.ФИОСотруд Get end)
                return result;
            }
            set
            {
                // *** Start programmer edit section *** (Сотрудники.ФИОСотруд Set start)

                // *** End programmer edit section *** (Сотрудники.ФИОСотруд Set start)
                this.fФИОСотруд = value;
                // *** Start programmer edit section *** (Сотрудники.ФИОСотруд Set end)

                // *** End programmer edit section *** (Сотрудники.ФИОСотруд Set end)
            }
        }
        
        /// <summary>
        /// Class views container.
        /// </summary>
        public class Views
        {
            
            /// <summary>
            /// "СотрудникиE" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиE
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиE", typeof(IIS.Vapro.Сотрудники));
                }
            }
            
            /// <summary>
            /// "СотрудникиL" view.
            /// </summary>
            public static ICSSoft.STORMNET.View СотрудникиL
            {
                get
                {
                    return ICSSoft.STORMNET.Information.GetView("СотрудникиL", typeof(IIS.Vapro.Сотрудники));
                }
            }
        }
    }
}
